/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-02-16T16:32:15.715542+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function toggleTagOnImage(params: types.ToggleTagOnImageParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.ToggleTagOnImageParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('toggle_tag_on_image', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createTag(params: types.CreateTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.CreateTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('create_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchUserTags(hooks?: CommandHooks<types.TagDto[]>): Promise<types.TagDto[]> {
  try {
    const data = await invoke<types.TagDto[]>('fetch_user_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchSystemTags(hooks?: CommandHooks<types.TagDto[]>): Promise<types.TagDto[]> {
  try {
    const data = await invoke<types.TagDto[]>('fetch_system_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function deleteTag(params: types.DeleteTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function importImages(params: types.ImportImagesParams, hooks?: CommandHooks<types.ImportSummaryDto>): Promise<types.ImportSummaryDto> {
  try {
    const result = types.ImportImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImportSummaryDto>('import_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function searchImages(params: types.SearchImagesParams, hooks?: CommandHooks<types.ImageSearchResult>): Promise<types.ImageSearchResult> {
  try {
    const result = types.SearchImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageSearchResult>('search_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchImageByIds(params: types.FetchImageByIdsParams, hooks?: CommandHooks<types.ImageDto[]>): Promise<types.ImageDto[]> {
  try {
    const result = types.FetchImageByIdsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageDto[]>('fetch_image_by_ids', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchImages(params: types.FetchImagesParams, hooks?: CommandHooks<types.PaginatedImages>): Promise<types.PaginatedImages> {
  try {
    const result = types.FetchImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedImages>('fetch_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchImagesWithTag(params: types.FetchImagesWithTagParams, hooks?: CommandHooks<types.PaginatedImages>): Promise<types.PaginatedImages> {
  try {
    const result = types.FetchImagesWithTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedImages>('fetch_images_with_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchImagesGroupedByHash(params: types.FetchImagesGroupedByHashParams, hooks?: CommandHooks<types.PaginatedImageHashGroups>): Promise<types.PaginatedImageHashGroups> {
  try {
    const result = types.FetchImagesGroupedByHashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.PaginatedImageHashGroups>('fetch_images_grouped_by_hash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


