/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-02-17T16:28:51.941219+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const SearchOrderBySchema = z.enum(["Asc", "Desc"]);

export const ImageSortBySchema = z.enum(["FileName", "Size", "CreatedAt"]);

export const GalleryImageSchema = z.object({
  imageId: z.coerce.number(),
  fileName: z.string(),
  imagePath: z.string(),
  imageSize: z.string(),
  resolution: z.string(),
  thumbnailPath: z.string(),
  createdAt: z.string(),
  isFavorite: z.coerce.boolean(),
});

export type GalleryImage = z.infer<typeof GalleryImageSchema>;

export const ImageDtoSchema = z.object({
  id: z.coerce.number(),
  path: z.string(),
  fileName: z.string(),
  size: z.string(),
  resolution: z.string(),
  thumbnailPath: z.string(),
  createdAt: z.string(),
});

export type ImageDto = z.infer<typeof ImageDtoSchema>;

export const ImageCursorSchema = z.object({
  createdAt: z.string(),
  id: z.coerce.number(),
});

export type ImageCursor = z.infer<typeof ImageCursorSchema>;

export const PaginatedImagesSchema = z.object({
  data: z.array(ImageDtoSchema),
  nextCursor: ImageCursorSchema.optional(),
});

export type PaginatedImages = z.infer<typeof PaginatedImagesSchema>;

export const ImageFiltersSchema = z.object({
  file_names: z.array(z.string()),
  tag_ids: z.array(z.coerce.number()),
});

export type ImageFilters = z.infer<typeof ImageFiltersSchema>;

export const ImageSearchQuerySchema = z.object({
  filters: ImageFiltersSchema,
  sort_by: ImageSortBySchema.optional(),
  order: SearchOrderBySchema.optional(),
  limit: z.coerce.number(),
});

export type ImageSearchQuery = z.infer<typeof ImageSearchQuerySchema>;

export const ImageSearchCursorSchema = z.object({
  last_value: z.string(),
  id: z.coerce.number(),
});

export type ImageSearchCursor = z.infer<typeof ImageSearchCursorSchema>;

export const ImageSearchResultSchema = z.object({
  next_cursor: ImageSearchCursorSchema.optional(),
  data: z.array(ImageDtoSchema),
});

export type ImageSearchResult = z.infer<typeof ImageSearchResultSchema>;

export const TagDtoSchema = z.object({
  id: z.coerce.number(),
  tagName: z.string(),
  tagColor: z.string(),
  imageCount: z.coerce.number(),
});

export type TagDto = z.infer<typeof TagDtoSchema>;

export const ImportSummaryDtoSchema = z.object({
  totalScanned: z.coerce.number(),
  totalImported: z.coerce.number(),
  failed: z.coerce.number(),
  skipped: z.coerce.number(),
});

export type ImportSummaryDto = z.infer<typeof ImportSummaryDtoSchema>;

export const GalleryImageResultSchema = z.object({
  data: z.array(GalleryImageSchema),
  nextCursor: ImageCursorSchema.optional(),
});

export type GalleryImageResult = z.infer<typeof GalleryImageResultSchema>;

export const PaginatedImageHashGroupsSchema = z.object({
  data: z.array(z.array(ImageDtoSchema)),
  next_cursor: z.coerce.number().optional(),
});

export type PaginatedImageHashGroups = z.infer<typeof PaginatedImageHashGroupsSchema>;


export const ToggleTagOnImageParamsSchema = z.object({
  imageId: z.coerce.number(),tagId: z.coerce.number(),
});

export const CreateTagParamsSchema = z.object({
  tagText: z.string(),
});

export const DeleteTagParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const ImportImagesParamsSchema = z.object({
  paths: z.array(z.string()),
});

export const SearchImagesParamsSchema = z.object({
  query: ImageSearchQuerySchema,cursor: ImageSearchCursorSchema.optional().optional(),
});

export const FetchImageByIdsParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const FetchImagesParamsSchema = z.object({
  limit: z.coerce.number(),cursor: ImageCursorSchema.optional().optional(),
});

export const FetchImagesWithTagParamsSchema = z.object({
  tagId: z.coerce.number(),limit: z.coerce.number(),cursor: ImageCursorSchema.optional().optional(),
});

export const FetchImagesGroupedByHashParamsSchema = z.object({
  limit: z.coerce.number(),nextCursor: z.coerce.number().optional().optional(),
});

export const FetchGalleryParamsSchema = z.object({
  cursor: ImageCursorSchema.optional().optional(),
});

export const ToggleFavoriteParamsSchema = z.object({
  imageId: z.coerce.number(),
});




export type ToggleTagOnImageParams = z.infer<typeof ToggleTagOnImageParamsSchema>;

export type CreateTagParams = z.infer<typeof CreateTagParamsSchema>;

export type DeleteTagParams = z.infer<typeof DeleteTagParamsSchema>;

export type ImportImagesParams = z.infer<typeof ImportImagesParamsSchema>;

export type SearchImagesParams = z.infer<typeof SearchImagesParamsSchema>;

export type FetchImageByIdsParams = z.infer<typeof FetchImageByIdsParamsSchema>;

export type FetchImagesParams = z.infer<typeof FetchImagesParamsSchema>;

export type FetchImagesWithTagParams = z.infer<typeof FetchImagesWithTagParamsSchema>;

export type FetchImagesGroupedByHashParams = z.infer<typeof FetchImagesGroupedByHashParamsSchema>;

export type FetchGalleryParams = z.infer<typeof FetchGalleryParamsSchema>;

export type ToggleFavoriteParams = z.infer<typeof ToggleFavoriteParamsSchema>;

