/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-02-25T16:13:06.893151+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const CreatedAtCursorSchema = z.object({
  createdAt: z.string(),
  id: z.coerce.number(),
});

export type CreatedAtCursor = z.infer<typeof CreatedAtCursorSchema>;

export const ImportSummarySchema = z.object({
  totalScanned: z.coerce.number(),
  totalImported: z.coerce.number(),
  failed: z.coerce.number(),
  skipped: z.coerce.number(),
});

export type ImportSummary = z.infer<typeof ImportSummarySchema>;

export const ImageItemSchema = z.object({
  id: z.coerce.number(),
  fileName: z.string(),
  filePath: z.string(),
  size: z.string(),
  resolution: z.string(),
  thumbnailPath: z.string(),
  createdAt: z.string(),
  isFavorite: z.coerce.boolean(),
});

export type ImageItem = z.infer<typeof ImageItemSchema>;

export const ImageItemResultSchema = z.object({
  data: z.array(ImageItemSchema),
  nextCursor: CreatedAtCursorSchema.optional(),
});

export type ImageItemResult = z.infer<typeof ImageItemResultSchema>;

export const TagItemSchema = z.object({
  id: z.coerce.number(),
  tagName: z.string(),
  tagColor: z.string(),
  imageCount: z.coerce.number(),
});

export type TagItem = z.infer<typeof TagItemSchema>;


export const ImportImagesParamsSchema = z.object({
  paths: z.array(z.string()),
});

export const ToggleFavoriteParamsSchema = z.object({
  imageId: z.coerce.number(),
});

export const SoftDeleteImageParamsSchema = z.object({
  imageId: z.coerce.number(),
});

export const UndoSoftDeleteImageParamsSchema = z.object({
  imageId: z.coerce.number(),
});

export const SoftDeleteImagesParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const UndoSoftDeleteImagesParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const DeleteImagesParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const CreateTagParamsSchema = z.object({
  tagName: z.string(),color: z.string(),
});

export const EditTagParamsSchema = z.object({
  tagId: z.coerce.number(),tagName: z.string().optional().optional(),tagColor: z.string().optional().optional(),
});

export const SoftDeleteTagParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const UndoDeleteTagParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const DeleteTagParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const ToggleTagParamsSchema = z.object({
  imageId: z.coerce.number(),tagId: z.coerce.number(),
});

export const AttachTagParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),tagId: z.coerce.number(),
});

export const RemoveTagParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),tagId: z.coerce.number(),
});

export const FetchAttachedTagsParamsSchema = z.object({
  imageId: z.coerce.number(),limit: z.coerce.number().optional().optional(),
});

export const FetchAvailableTagsParamsSchema = z.object({
  imageId: z.coerce.number(),limit: z.coerce.number().optional().optional(),
});

export const AttachedTagsParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),limit: z.coerce.number().optional().optional(),
});

export const AvailableTagsParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),limit: z.coerce.number().optional().optional(),
});

export const FetchGalleryParamsSchema = z.object({
  cursor: CreatedAtCursorSchema.optional().optional(),
});

export const FetchBinParamsSchema = z.object({
  cursor: CreatedAtCursorSchema.optional().optional(),
});

export const FetchFavoritesParamsSchema = z.object({
  cursor: CreatedAtCursorSchema.optional().optional(),
});

export const FetchTagGalleryParamsSchema = z.object({
  tagId: z.coerce.number(),cursor: CreatedAtCursorSchema.optional().optional(),
});




export type ImportImagesParams = z.infer<typeof ImportImagesParamsSchema>;

export type ToggleFavoriteParams = z.infer<typeof ToggleFavoriteParamsSchema>;

export type SoftDeleteImageParams = z.infer<typeof SoftDeleteImageParamsSchema>;

export type UndoSoftDeleteImageParams = z.infer<typeof UndoSoftDeleteImageParamsSchema>;

export type SoftDeleteImagesParams = z.infer<typeof SoftDeleteImagesParamsSchema>;

export type UndoSoftDeleteImagesParams = z.infer<typeof UndoSoftDeleteImagesParamsSchema>;

export type DeleteImagesParams = z.infer<typeof DeleteImagesParamsSchema>;

export type CreateTagParams = z.infer<typeof CreateTagParamsSchema>;

export type EditTagParams = z.infer<typeof EditTagParamsSchema>;

export type SoftDeleteTagParams = z.infer<typeof SoftDeleteTagParamsSchema>;

export type UndoDeleteTagParams = z.infer<typeof UndoDeleteTagParamsSchema>;

export type DeleteTagParams = z.infer<typeof DeleteTagParamsSchema>;

export type ToggleTagParams = z.infer<typeof ToggleTagParamsSchema>;

export type AttachTagParams = z.infer<typeof AttachTagParamsSchema>;

export type RemoveTagParams = z.infer<typeof RemoveTagParamsSchema>;

export type FetchAttachedTagsParams = z.infer<typeof FetchAttachedTagsParamsSchema>;

export type FetchAvailableTagsParams = z.infer<typeof FetchAvailableTagsParamsSchema>;

export type AttachedTagsParams = z.infer<typeof AttachedTagsParamsSchema>;

export type AvailableTagsParams = z.infer<typeof AvailableTagsParamsSchema>;

export type FetchGalleryParams = z.infer<typeof FetchGalleryParamsSchema>;

export type FetchBinParams = z.infer<typeof FetchBinParamsSchema>;

export type FetchFavoritesParams = z.infer<typeof FetchFavoritesParamsSchema>;

export type FetchTagGalleryParams = z.infer<typeof FetchTagGalleryParamsSchema>;

