/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-02-14T08:16:20.527259+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const ImportSummaryDtoSchema = z.object({
  totalScanned: z.coerce.number(),
  totalImported: z.coerce.number(),
  failed: z.coerce.number(),
  skipped: z.coerce.number(),
});

export type ImportSummaryDto = z.infer<typeof ImportSummaryDtoSchema>;

export const ImageDtoSchema = z.object({
  id: z.coerce.number(),
  path: z.string(),
  size: z.string(),
  resolution: z.string(),
  thumbnailPath: z.string(),
  createdAt: z.string(),
});

export type ImageDto = z.infer<typeof ImageDtoSchema>;

export const ImageCursorSchema = z.object({
  createdAt: z.string(),
  id: z.coerce.number(),
});

export type ImageCursor = z.infer<typeof ImageCursorSchema>;

export const PaginatedImagesSchema = z.object({
  data: z.array(ImageDtoSchema),
  nextCursor: ImageCursorSchema.optional(),
});

export type PaginatedImages = z.infer<typeof PaginatedImagesSchema>;


export const ImportImagesParamsSchema = z.object({
  paths: z.array(z.string()),
});

export const FetchImagesParamsSchema = z.object({
  limit: z.coerce.number(),cursor: ImageCursorSchema.optional().optional(),
});




export type ImportImagesParams = z.infer<typeof ImportImagesParamsSchema>;

export type FetchImagesParams = z.infer<typeof FetchImagesParamsSchema>;

