/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-02-15T05:27:49.796619+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const ImportSummaryDtoSchema = z.object({
  totalScanned: z.coerce.number(),
  totalImported: z.coerce.number(),
  failed: z.coerce.number(),
  skipped: z.coerce.number(),
});

export type ImportSummaryDto = z.infer<typeof ImportSummaryDtoSchema>;

export const ImageDtoSchema = z.object({
  id: z.coerce.number(),
  path: z.string(),
  size: z.string(),
  resolution: z.string(),
  thumbnailPath: z.string(),
  createdAt: z.string(),
});

export type ImageDto = z.infer<typeof ImageDtoSchema>;

export const ImageCursorSchema = z.object({
  createdAt: z.string(),
  id: z.coerce.number(),
});

export type ImageCursor = z.infer<typeof ImageCursorSchema>;

export const PaginatedImagesSchema = z.object({
  data: z.array(ImageDtoSchema),
  nextCursor: ImageCursorSchema.optional(),
});

export type PaginatedImages = z.infer<typeof PaginatedImagesSchema>;

export const PaginatedImageHashGroupsSchema = z.object({
  data: z.array(z.array(ImageDtoSchema)),
  next_cursor: z.coerce.number().optional(),
});

export type PaginatedImageHashGroups = z.infer<typeof PaginatedImageHashGroupsSchema>;


export const ImportImagesParamsSchema = z.object({
  paths: z.array(z.string()),
});

export const FetchImagesParamsSchema = z.object({
  limit: z.coerce.number(),cursor: ImageCursorSchema.optional().optional(),
});

export const FetchImagesGroupedByHashParamsSchema = z.object({
  limit: z.coerce.number(),nextCursor: z.coerce.number().optional().optional(),
});




export type ImportImagesParams = z.infer<typeof ImportImagesParamsSchema>;

export type FetchImagesParams = z.infer<typeof FetchImagesParamsSchema>;

export type FetchImagesGroupedByHashParams = z.infer<typeof FetchImagesGroupedByHashParamsSchema>;

