/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-03-01T10:19:17.631587+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function toggleTag(params: types.ToggleTagParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.ToggleTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('toggle_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function attachedTags(params: types.AttachedTagsParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.AttachedTagsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('attached_tags', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function availableTags(params: types.AvailableTagsParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.AvailableTagsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('available_tags', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function attachedTagsMultiple(params: types.AttachedTagsMultipleParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.AttachedTagsMultipleParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('attached_tags_multiple', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function availableTagsMultiple(params: types.AvailableTagsMultipleParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.AvailableTagsMultipleParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('available_tags_multiple', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function attachTag(params: types.AttachTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.AttachTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('attach_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function removeTag(params: types.RemoveTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.RemoveTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('remove_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function importImages(params: types.ImportImagesParams, hooks?: CommandHooks<types.ImportSummary>): Promise<types.ImportSummary> {
  try {
    const result = types.ImportImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImportSummary>('import_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function toggleFavorite(params: types.ToggleFavoriteParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.ToggleFavoriteParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('toggle_favorite', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function moveToTrash(params: types.MoveToTrashParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.MoveToTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('move_to_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function restoreFromTrash(params: types.RestoreFromTrashParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.RestoreFromTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('restore_from_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function deleteFromTrash(params: types.DeleteFromTrashParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteFromTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_from_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function emptyTrash(hooks?: CommandHooks<void>): Promise<void> {
  try {
    const data = await invoke<void>('empty_trash');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function createTag(params: types.CreateTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.CreateTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('create_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function editTag(params: types.EditTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.EditTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('edit_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function markTagInactive(params: types.MarkTagInactiveParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.MarkTagInactiveParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('mark_tag_inactive', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function markTagActive(params: types.MarkTagActiveParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.MarkTagActiveParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('mark_tag_active', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchActiveTags(hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const data = await invoke<types.TagItem[]>('fetch_active_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchInactiveTags(hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const data = await invoke<types.TagItem[]>('fetch_inactive_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function deleteTag(params: types.DeleteTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchTopTags(hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const data = await invoke<types.TagItem[]>('fetch_top_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchAllImages(params: types.FetchAllImagesParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchAllImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_all_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchTrash(params: types.FetchTrashParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchFavorites(params: types.FetchFavoritesParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchFavoritesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_favorites', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchTagImages(params: types.FetchTagImagesParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchTagImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_tag_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


