/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-03-01T07:38:06.781578+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import { ZodError } from 'zod';
import * as types from './types';

export interface CommandHooks<T> {
  /** Called when Zod schema validation fails */
  onValidationError?: (error: ZodError) => void;

  /** Called when Tauri invoke fails (Rust error, serialization, etc.) */
  onInvokeError?: (error: unknown) => void;

  /** Called when command succeeds */
  onSuccess?: (result: T) => void;

  /** Called after command settles (success or error) */
  onSettled?: () => void;
}

export async function createTag(params: types.CreateTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.CreateTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('create_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function editTag(params: types.EditTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.EditTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('edit_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function softDeleteTag(params: types.SoftDeleteTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.SoftDeleteTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('soft_delete_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function undoDeleteTag(params: types.UndoDeleteTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.UndoDeleteTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('undo_delete_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function deleteTag(params: types.DeleteTagParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.DeleteTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('delete_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchTopTags(hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const data = await invoke<types.TagItem[]>('fetch_top_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchAllTags(hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const data = await invoke<types.TagItem[]>('fetch_all_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function fetchDeletedTags(hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const data = await invoke<types.TagItem[]>('fetch_deleted_tags');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function toggleTag(params: types.ToggleTagParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.ToggleTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('toggle_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function attachTag(params: types.AttachTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.AttachTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('attach_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function removeTag(params: types.RemoveTagParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.RemoveTagParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('remove_tag', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchAttachedTags(params: types.FetchAttachedTagsParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.FetchAttachedTagsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('fetch_attached_tags', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchAvailableTags(params: types.FetchAvailableTagsParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.FetchAvailableTagsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('fetch_available_tags', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function attachedTags(params: types.AttachedTagsParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.AttachedTagsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('attached_tags', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function availableTags(params: types.AvailableTagsParams, hooks?: CommandHooks<types.TagItem[]>): Promise<types.TagItem[]> {
  try {
    const result = types.AvailableTagsParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.TagItem[]>('available_tags', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function importImages(params: types.ImportImagesParams, hooks?: CommandHooks<types.ImportSummary>): Promise<types.ImportSummary> {
  try {
    const result = types.ImportImagesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImportSummary>('import_images', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function toggleFavorite(params: types.ToggleFavoriteParams, hooks?: CommandHooks<boolean>): Promise<boolean> {
  try {
    const result = types.ToggleFavoriteParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<boolean>('toggle_favorite', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function moveToTrash(params: types.MoveToTrashParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.MoveToTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('move_to_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function restoreFromTrash(params: types.RestoreFromTrashParams, hooks?: CommandHooks<number>): Promise<number> {
  try {
    const result = types.RestoreFromTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<number>('restore_from_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function removeFromTrash(params: types.RemoveFromTrashParams, hooks?: CommandHooks<void>): Promise<void> {
  try {
    const result = types.RemoveFromTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<void>('remove_from_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}



export async function emptyTrash(hooks?: CommandHooks<void>): Promise<void> {
  try {
    const data = await invoke<void>('empty_trash');
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    hooks?.onInvokeError?.(error);
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchAll(params: types.FetchAllParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchAllParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_all', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchTrash(params: types.FetchTrashParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchTrashParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_trash', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchFavorites(params: types.FetchFavoritesParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchFavoritesParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_favorites', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


export async function fetchTagGallery(params: types.FetchTagGalleryParams, hooks?: CommandHooks<types.ImageItemResult>): Promise<types.ImageItemResult> {
  try {
    const result = types.FetchTagGalleryParamsSchema.safeParse(params);

    if (!result.success) {
      hooks?.onValidationError?.(result.error);
      throw result.error;
    }
    const data = await invoke<types.ImageItemResult>('fetch_tag_gallery', result.data);
    hooks?.onSuccess?.(data);
    return data;
  } catch (error) {
    if (!(error instanceof ZodError)) {
      hooks?.onInvokeError?.(error);
    }
    throw error;
  } finally {
    hooks?.onSettled?.();
  }
}


