/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.4.1
 * Generated at: 2026-03-01T10:19:17.631439+00:00
 * Generator: zod
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { z } from 'zod';


export const CreatedAtCursorSchema = z.object({
  createdAt: z.string(),
  id: z.coerce.number(),
});

export type CreatedAtCursor = z.infer<typeof CreatedAtCursorSchema>;

export const ImageItemSchema = z.object({
  id: z.coerce.number(),
  fileName: z.string(),
  filePath: z.string(),
  size: z.string(),
  resolution: z.string(),
  thumbnailPath: z.string(),
  createdAt: z.string(),
  isFavorite: z.coerce.boolean(),
});

export type ImageItem = z.infer<typeof ImageItemSchema>;

export const ImageItemResultSchema = z.object({
  data: z.array(ImageItemSchema),
  nextCursor: CreatedAtCursorSchema.optional(),
});

export type ImageItemResult = z.infer<typeof ImageItemResultSchema>;

export const ImportSummarySchema = z.object({
  totalScanned: z.coerce.number(),
  totalImported: z.coerce.number(),
  failed: z.coerce.number(),
  skipped: z.coerce.number(),
});

export type ImportSummary = z.infer<typeof ImportSummarySchema>;

export const TagItemSchema = z.object({
  id: z.coerce.number(),
  tagName: z.string(),
  tagColor: z.string(),
  imageCount: z.coerce.number(),
});

export type TagItem = z.infer<typeof TagItemSchema>;


export const ToggleTagParamsSchema = z.object({
  imageId: z.coerce.number(),tagId: z.coerce.number(),
});

export const AttachedTagsParamsSchema = z.object({
  imageId: z.coerce.number(),limit: z.coerce.number().optional().optional(),
});

export const AvailableTagsParamsSchema = z.object({
  imageId: z.coerce.number(),limit: z.coerce.number().optional().optional(),
});

export const AttachedTagsMultipleParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),limit: z.coerce.number().optional().optional(),
});

export const AvailableTagsMultipleParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),limit: z.coerce.number().optional().optional(),
});

export const AttachTagParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),tagId: z.coerce.number(),
});

export const RemoveTagParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),tagId: z.coerce.number(),
});

export const ImportImagesParamsSchema = z.object({
  paths: z.array(z.string()),
});

export const ToggleFavoriteParamsSchema = z.object({
  imageId: z.coerce.number(),
});

export const MoveToTrashParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const RestoreFromTrashParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const DeleteFromTrashParamsSchema = z.object({
  imageIds: z.array(z.coerce.number()),
});

export const CreateTagParamsSchema = z.object({
  tagName: z.string(),color: z.string(),
});

export const EditTagParamsSchema = z.object({
  tagId: z.coerce.number(),tagName: z.string().optional().optional(),tagColor: z.string().optional().optional(),
});

export const MarkTagInactiveParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const MarkTagActiveParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const DeleteTagParamsSchema = z.object({
  tagId: z.coerce.number(),
});

export const FetchAllImagesParamsSchema = z.object({
  cursor: CreatedAtCursorSchema.optional().optional(),
});

export const FetchTrashParamsSchema = z.object({
  cursor: CreatedAtCursorSchema.optional().optional(),
});

export const FetchFavoritesParamsSchema = z.object({
  cursor: CreatedAtCursorSchema.optional().optional(),
});

export const FetchTagImagesParamsSchema = z.object({
  tagId: z.coerce.number(),cursor: CreatedAtCursorSchema.optional().optional(),
});




export type ToggleTagParams = z.infer<typeof ToggleTagParamsSchema>;

export type AttachedTagsParams = z.infer<typeof AttachedTagsParamsSchema>;

export type AvailableTagsParams = z.infer<typeof AvailableTagsParamsSchema>;

export type AttachedTagsMultipleParams = z.infer<typeof AttachedTagsMultipleParamsSchema>;

export type AvailableTagsMultipleParams = z.infer<typeof AvailableTagsMultipleParamsSchema>;

export type AttachTagParams = z.infer<typeof AttachTagParamsSchema>;

export type RemoveTagParams = z.infer<typeof RemoveTagParamsSchema>;

export type ImportImagesParams = z.infer<typeof ImportImagesParamsSchema>;

export type ToggleFavoriteParams = z.infer<typeof ToggleFavoriteParamsSchema>;

export type MoveToTrashParams = z.infer<typeof MoveToTrashParamsSchema>;

export type RestoreFromTrashParams = z.infer<typeof RestoreFromTrashParamsSchema>;

export type DeleteFromTrashParams = z.infer<typeof DeleteFromTrashParamsSchema>;

export type CreateTagParams = z.infer<typeof CreateTagParamsSchema>;

export type EditTagParams = z.infer<typeof EditTagParamsSchema>;

export type MarkTagInactiveParams = z.infer<typeof MarkTagInactiveParamsSchema>;

export type MarkTagActiveParams = z.infer<typeof MarkTagActiveParamsSchema>;

export type DeleteTagParams = z.infer<typeof DeleteTagParamsSchema>;

export type FetchAllImagesParams = z.infer<typeof FetchAllImagesParamsSchema>;

export type FetchTrashParams = z.infer<typeof FetchTrashParamsSchema>;

export type FetchFavoritesParams = z.infer<typeof FetchFavoritesParamsSchema>;

export type FetchTagImagesParams = z.infer<typeof FetchTagImagesParamsSchema>;

